/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author NITISH
 */
public class EditAllItem extends javax.swing.JFrame {
    String Itemid;
    File file;

    /**
     * Creates new form EditAllItem
     */
    public EditAllItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Back");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 62, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No.", "Item Id", "Item name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 351, 302));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 104, 188, 31));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 153, 188, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Cloth", "Toy", "Fruit", "Food" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 222, 188, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 274, 188, 62));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 382, 188, 32));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 464, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Default Item.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 81, 145, 161));

        jButton2.setText("Select Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 274, -1, -1));

        jLabel3.setText("Change Image ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 320, -1, -1));

        jLabel4.setText("name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 112, -1, -1));

        jLabel5.setText("price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 161, -1, -1));

        jLabel6.setText("Categ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 225, -1, -1));

        jLabel7.setText("Desc");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 288, -1, -1));

        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 391, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\NITISH\\Desktop\\Images\\edit item kr.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -40, 980, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        AdminProfile ad=new AdminProfile();
        ad.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DefaultTableModel dtm=( DefaultTableModel)jTable1.getModel();
        String Itemidd,Itemname;
        int srno=0;
        try
            (
                Connection con =dbconnection.DbConnection.getConnection();
                PreparedStatement ps=con.prepareStatement("select * from items");
                ResultSet rs=ps.executeQuery();
                )
        {
            while(rs.next())
            {
                srno=srno+1;
               Itemidd =rs.getString("Item_id");
               Itemname=rs.getString("Item_name");
               Object[]o={srno,Itemidd,Itemname};
               dtm.addRow(o);
            }
            
        }
            catch(Exception e)
                    {
                    e.printStackTrace();
                    }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
         Itemid=(String)jTable1.getValueAt(row, 1);
        String itemname,itemprice,itemdesc,itemqnty, itemcategory,itemimage;
         try
            (
                Connection con =dbconnection.DbConnection.getConnection();
                PreparedStatement ps=con.prepareStatement("select * from items where Item_id='"+Itemid+"'");
                ResultSet rs=ps.executeQuery();
                )
        {
            if(rs.next())
            {
             
             
               itemname=rs.getString("Item_name");
               itemprice=rs.getString("Item_price");
               itemdesc=rs.getString("Item_desc");
               itemqnty=rs.getString("Item_Quantity");
               itemcategory=rs.getString("Item_category");
               BufferedImage im=ImageIO.read(rs.getBinaryStream("Item_image"));
               jLabel2.setIcon(new ImageIcon(im.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT)));
                
               
              
               jTextArea1.setText(itemdesc);
               jTextField1.setText(itemname);
               jTextField2.setText(itemprice);
               jTextField3.setText(itemqnty);
               jComboBox1.setSelectedItem(itemcategory);
               
               
               
               
               
            }
            
        }
            catch(Exception e)
                    {
                    e.printStackTrace();
                    }
        
           
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
      String Item_name=jTextField1.getText();
        String Item_price=jTextField2.getText();///ye sari chije get ho gyi 
        String category=(String)jComboBox1.getSelectedItem();//type cast 
        String  desc =jTextArea1.getText();
        String Quantity=jTextField3.getText();
       
        FileInputStream fis=null;
        if(file!=null)
        {
             try
        {
            fis=new FileInputStream(file);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
       
        if(fis!=null)
        {
            
        
       
        try    
                (
                Connection con=dbconnection.DbConnection.getConnection();
                PreparedStatement ps=con.prepareStatement("update items set Item_name=?, Item_price=?,Item_category=?,Item_desc=?,Item_Quantity=?,Item_image=? where Item_id=?");
                )
        {
            ps.setString(1, Item_name);
            ps.setString(2, Item_price);
            ps.setString(3, category);
            ps.setString(4, desc);
            ps.setString(5, Quantity);
            ps.setString(7, Itemid);
            ps.setBinaryStream(6,fis,file.length());
            
           
            int i=ps.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Item updated successfully");
                
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
               
                jTextArea1.setText("");
                jComboBox1.setSelectedIndex(0);
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Default Item.png")));
               
            }
            else 
            {
             JOptionPane.showMessageDialog(rootPane, "Item not  updated successfully","ERROR",JOptionPane.ERROR_MESSAGE);

            }
            
            
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        }
        else
        {
             try    
                (
                Connection con=dbconnection.DbConnection.getConnection();
                PreparedStatement ps=con.prepareStatement("update items set Item_name=?, Item_price=?,Item_category=?,Item_desc=?,Item_Quantity=? where Item_id=?");
                )
        {
            ps.setString(1, Item_name);
            ps.setString(2, Item_price);
            ps.setString(3, category);
            ps.setString(4, desc);
            ps.setString(5, Quantity);
            ps.setString(6, Itemid);
           
            
           
            int i=ps.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Item updated successfully");
                
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
               
                jTextArea1.setText("");
                jComboBox1.setSelectedIndex(0);
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Default Item.png")));
               
            }
            else 
            {
             JOptionPane.showMessageDialog(rootPane, "Item not  updated successfully","ERROR",JOptionPane.ERROR_MESSAGE);

            }
            
            
            
        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
        JFileChooser filechooser=new JFileChooser();
        filechooser.showOpenDialog(rootPane);
        file=filechooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_DEFAULT));
        jLabel2.setIcon(imageIcon);
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAllItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAllItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAllItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAllItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAllItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
